telegram:
  weather-bot:
    username: user
    token: ${BOT_TOKEN:}

client:
  open-meteo:
    base-url: ${OPEN_METEO_BASE_URL:}

mermaid-statemachine:
  settings:
    schema:
      state-configuration-config:
        validate-unused-action-beans: error
        validate-states-without-action: error

notification:
  check-sec: 60
  schedule: 12h